package org.lanmei.seckill.dao.mapper;

import java.util.Date;
import java.util.List;

import javax.print.DocFlavor.STRING;

import org.apache.ibatis.annotations.Param;
import org.lanmei.seckill.dao.model.Seckill;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.PathVariable;

@Repository
public interface SeckillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer seckillId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill
	 * @mbg.generated
	 */
	int insert(Seckill record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill
	 * @mbg.generated
	 */
	Seckill selectByPrimaryKey(Integer seckillId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill
	 * @mbg.generated
	 */
	List<Seckill> selectAll();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seckill
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Seckill record);
	/**
	 * 获取已经结束的秒杀活动
	 * @param currentTime 当前时间
	 * @return List<Seckill>列表
	 */
	List<Seckill>  selectFinish(Date  currentTime);
	/**
	 * 获取还未结束的秒杀活动 当前时间
	 * @param currentTime
	 * @return List<Seckill>列表
	 */
	List<Seckill>  selectUnFinish(Date  currentTime);
	/**
	 * 库存减1
	 * @param seckillId
	 * @return 影响的条数 0 / 1
	 */
	int reduceStock(@Param("seckillId") Integer seckillId,@Param("currentTime") Date currentTime);
	
}