package org.lanmei.admin.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_admin
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CmsAdmin {

	/**
	 * Database Column Remarks: 管理员ID This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.admin_id
	 * @mbg.generated
	 */
	private Integer adminId;
	/**
	 * Database Column Remarks: 管理员工号 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.login_jobNum
	 * @mbg.generated
	 */
	private String loginJobnum;
	/**
	 * Database Column Remarks: 管理员登录密码 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.admin_password
	 * @mbg.generated
	 */
	private String adminPassword;
	/**
	 * Database Column Remarks: 密码加密的盐 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.password_salt
	 * @mbg.generated
	 */
	private String passwordSalt;
	/**
	 * Database Column Remarks: 管理员昵称 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.nick_name
	 * @mbg.generated
	 */
	private String nickName;
	/**
	 * Database Column Remarks: 真实姓名 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.actual_name
	 * @mbg.generated
	 */
	private String actualName;
	/**
	 * Database Column Remarks: 创建人员 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.create_admin
	 * @mbg.generated
	 */
	private Integer createAdmin;
	/**
	 * Database Column Remarks: 注册时邀请码 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.invitation_code
	 * @mbg.generated
	 */
	private String invitationCode;
	/**
	 * Database Column Remarks: 性别-男/女 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.gender
	 * @mbg.generated
	 */
	private Byte gender;
	/**
	 * Database Column Remarks: 年龄 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.age
	 * @mbg.generated
	 */
	private Byte age;
	/**
	 * Database Column Remarks: 头像 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.head_portrait
	 * @mbg.generated
	 */
	private String headPortrait;
	/**
	 * Database Column Remarks: 状态-待激活/正常状态/登录异常/禁止登录/注销状态 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.state
	 * @mbg.generated
	 */
	private String state;
	/**
	 * Database Column Remarks: 邮箱地址 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * Database Column Remarks: 邮箱激活状态-激活/未激活 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.email_is_activate
	 * @mbg.generated
	 */
	private Byte emailIsActivate;
	/**
	 * Database Column Remarks: 手机号码 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.phone_num
	 * @mbg.generated
	 */
	private String phoneNum;
	/**
	 * Database Column Remarks: 最后登录时间 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.last_login_time
	 * @mbg.generated
	 */
	private Date lastLoginTime;
	/**
	 * Database Column Remarks: 最后登录ip This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.last_login_ip
	 * @mbg.generated
	 */
	private String lastLoginIp;
	/**
	 * Database Column Remarks: 登录次数 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.login_count
	 * @mbg.generated
	 */
	private Integer loginCount;
	/**
	 * Database Column Remarks: 帐号生成时间 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.generate_time
	 * @mbg.generated
	 */
	private Date generateTime;
	/**
	 * Database Column Remarks: 帐号激活时间 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.activate_time
	 * @mbg.generated
	 */
	private Date activateTime;
	/**
	 * Database Column Remarks: 帐号注销时间 This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.colose_time
	 * @mbg.generated
	 */
	private Date coloseTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.admin_id
	 * @return  the value of cms_admin.admin_id
	 * @mbg.generated
	 */
	public Integer getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.admin_id
	 * @param adminId  the value for cms_admin.admin_id
	 * @mbg.generated
	 */
	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.login_jobNum
	 * @return  the value of cms_admin.login_jobNum
	 * @mbg.generated
	 */
	public String getLoginJobnum() {
		return loginJobnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.login_jobNum
	 * @param loginJobnum  the value for cms_admin.login_jobNum
	 * @mbg.generated
	 */
	public void setLoginJobnum(String loginJobnum) {
		this.loginJobnum = loginJobnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.admin_password
	 * @return  the value of cms_admin.admin_password
	 * @mbg.generated
	 */
	public String getAdminPassword() {
		return adminPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.admin_password
	 * @param adminPassword  the value for cms_admin.admin_password
	 * @mbg.generated
	 */
	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.password_salt
	 * @return  the value of cms_admin.password_salt
	 * @mbg.generated
	 */
	public String getPasswordSalt() {
		return passwordSalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.password_salt
	 * @param passwordSalt  the value for cms_admin.password_salt
	 * @mbg.generated
	 */
	public void setPasswordSalt(String passwordSalt) {
		this.passwordSalt = passwordSalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.nick_name
	 * @return  the value of cms_admin.nick_name
	 * @mbg.generated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.nick_name
	 * @param nickName  the value for cms_admin.nick_name
	 * @mbg.generated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.actual_name
	 * @return  the value of cms_admin.actual_name
	 * @mbg.generated
	 */
	public String getActualName() {
		return actualName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.actual_name
	 * @param actualName  the value for cms_admin.actual_name
	 * @mbg.generated
	 */
	public void setActualName(String actualName) {
		this.actualName = actualName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.create_admin
	 * @return  the value of cms_admin.create_admin
	 * @mbg.generated
	 */
	public Integer getCreateAdmin() {
		return createAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.create_admin
	 * @param createAdmin  the value for cms_admin.create_admin
	 * @mbg.generated
	 */
	public void setCreateAdmin(Integer createAdmin) {
		this.createAdmin = createAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.invitation_code
	 * @return  the value of cms_admin.invitation_code
	 * @mbg.generated
	 */
	public String getInvitationCode() {
		return invitationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.invitation_code
	 * @param invitationCode  the value for cms_admin.invitation_code
	 * @mbg.generated
	 */
	public void setInvitationCode(String invitationCode) {
		this.invitationCode = invitationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.gender
	 * @return  the value of cms_admin.gender
	 * @mbg.generated
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.gender
	 * @param gender  the value for cms_admin.gender
	 * @mbg.generated
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.age
	 * @return  the value of cms_admin.age
	 * @mbg.generated
	 */
	public Byte getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.age
	 * @param age  the value for cms_admin.age
	 * @mbg.generated
	 */
	public void setAge(Byte age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.head_portrait
	 * @return  the value of cms_admin.head_portrait
	 * @mbg.generated
	 */
	public String getHeadPortrait() {
		return headPortrait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.head_portrait
	 * @param headPortrait  the value for cms_admin.head_portrait
	 * @mbg.generated
	 */
	public void setHeadPortrait(String headPortrait) {
		this.headPortrait = headPortrait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.state
	 * @return  the value of cms_admin.state
	 * @mbg.generated
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.state
	 * @param state  the value for cms_admin.state
	 * @mbg.generated
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.email
	 * @return  the value of cms_admin.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.email
	 * @param email  the value for cms_admin.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.email_is_activate
	 * @return  the value of cms_admin.email_is_activate
	 * @mbg.generated
	 */
	public Byte getEmailIsActivate() {
		return emailIsActivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.email_is_activate
	 * @param emailIsActivate  the value for cms_admin.email_is_activate
	 * @mbg.generated
	 */
	public void setEmailIsActivate(Byte emailIsActivate) {
		this.emailIsActivate = emailIsActivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.phone_num
	 * @return  the value of cms_admin.phone_num
	 * @mbg.generated
	 */
	public String getPhoneNum() {
		return phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.phone_num
	 * @param phoneNum  the value for cms_admin.phone_num
	 * @mbg.generated
	 */
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.last_login_time
	 * @return  the value of cms_admin.last_login_time
	 * @mbg.generated
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.last_login_time
	 * @param lastLoginTime  the value for cms_admin.last_login_time
	 * @mbg.generated
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.last_login_ip
	 * @return  the value of cms_admin.last_login_ip
	 * @mbg.generated
	 */
	public String getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.last_login_ip
	 * @param lastLoginIp  the value for cms_admin.last_login_ip
	 * @mbg.generated
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.login_count
	 * @return  the value of cms_admin.login_count
	 * @mbg.generated
	 */
	public Integer getLoginCount() {
		return loginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.login_count
	 * @param loginCount  the value for cms_admin.login_count
	 * @mbg.generated
	 */
	public void setLoginCount(Integer loginCount) {
		this.loginCount = loginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.generate_time
	 * @return  the value of cms_admin.generate_time
	 * @mbg.generated
	 */
	public Date getGenerateTime() {
		return generateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.generate_time
	 * @param generateTime  the value for cms_admin.generate_time
	 * @mbg.generated
	 */
	public void setGenerateTime(Date generateTime) {
		this.generateTime = generateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.activate_time
	 * @return  the value of cms_admin.activate_time
	 * @mbg.generated
	 */
	public Date getActivateTime() {
		return activateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.activate_time
	 * @param activateTime  the value for cms_admin.activate_time
	 * @mbg.generated
	 */
	public void setActivateTime(Date activateTime) {
		this.activateTime = activateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.colose_time
	 * @return  the value of cms_admin.colose_time
	 * @mbg.generated
	 */
	public Date getColoseTime() {
		return coloseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.colose_time
	 * @param coloseTime  the value for cms_admin.colose_time
	 * @mbg.generated
	 */
	public void setColoseTime(Date coloseTime) {
		this.coloseTime = coloseTime;
	}
}