package com.lanmei.user.dao.model;

public class OsFavorites {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_favorites.favorites_id
     *
     * @mbggenerated
     */
    private Integer favoritesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_favorites.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_favorites.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_favorites.favorites_id
     *
     * @return the value of os_favorites.favorites_id
     *
     * @mbggenerated
     */
    public Integer getFavoritesId() {
        return favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_favorites.favorites_id
     *
     * @param favoritesId the value for os_favorites.favorites_id
     *
     * @mbggenerated
     */
    public void setFavoritesId(Integer favoritesId) {
        this.favoritesId = favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_favorites.user_id
     *
     * @return the value of os_favorites.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_favorites.user_id
     *
     * @param userId the value for os_favorites.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_favorites.commodity_id
     *
     * @return the value of os_favorites.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_favorites.commodity_id
     *
     * @param commodityId the value for os_favorites.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }
}