package com.lanmei.user.dao.model;

import java.util.Date;

public class OsReceiptAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.receipt_address_id
     *
     * @mbggenerated
     */
    private Integer receiptAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.district_id
     *
     * @mbggenerated
     */
    private Integer districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.district_name
     *
     * @mbggenerated
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.street_id
     *
     * @mbggenerated
     */
    private Integer streetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.street_name
     *
     * @mbggenerated
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.post_code
     *
     * @mbggenerated
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_receipt_address.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.receipt_address_id
     *
     * @return the value of os_receipt_address.receipt_address_id
     *
     * @mbggenerated
     */
    public Integer getReceiptAddressId() {
        return receiptAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.receipt_address_id
     *
     * @param receiptAddressId the value for os_receipt_address.receipt_address_id
     *
     * @mbggenerated
     */
    public void setReceiptAddressId(Integer receiptAddressId) {
        this.receiptAddressId = receiptAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.user_id
     *
     * @return the value of os_receipt_address.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.user_id
     *
     * @param userId the value for os_receipt_address.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.name
     *
     * @return the value of os_receipt_address.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.name
     *
     * @param name the value for os_receipt_address.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.phone_num
     *
     * @return the value of os_receipt_address.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.phone_num
     *
     * @param phoneNum the value for os_receipt_address.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.province_id
     *
     * @return the value of os_receipt_address.province_id
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.province_id
     *
     * @param provinceId the value for os_receipt_address.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.province_name
     *
     * @return the value of os_receipt_address.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.province_name
     *
     * @param provinceName the value for os_receipt_address.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.city_id
     *
     * @return the value of os_receipt_address.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.city_id
     *
     * @param cityId the value for os_receipt_address.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.city_name
     *
     * @return the value of os_receipt_address.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.city_name
     *
     * @param cityName the value for os_receipt_address.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.district_id
     *
     * @return the value of os_receipt_address.district_id
     *
     * @mbggenerated
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.district_id
     *
     * @param districtId the value for os_receipt_address.district_id
     *
     * @mbggenerated
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.district_name
     *
     * @return the value of os_receipt_address.district_name
     *
     * @mbggenerated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.district_name
     *
     * @param districtName the value for os_receipt_address.district_name
     *
     * @mbggenerated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.street_id
     *
     * @return the value of os_receipt_address.street_id
     *
     * @mbggenerated
     */
    public Integer getStreetId() {
        return streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.street_id
     *
     * @param streetId the value for os_receipt_address.street_id
     *
     * @mbggenerated
     */
    public void setStreetId(Integer streetId) {
        this.streetId = streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.street_name
     *
     * @return the value of os_receipt_address.street_name
     *
     * @mbggenerated
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.street_name
     *
     * @param streetName the value for os_receipt_address.street_name
     *
     * @mbggenerated
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.post_code
     *
     * @return the value of os_receipt_address.post_code
     *
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.post_code
     *
     * @param postCode the value for os_receipt_address.post_code
     *
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.create_time
     *
     * @return the value of os_receipt_address.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.create_time
     *
     * @param createTime the value for os_receipt_address.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_receipt_address.update_time
     *
     * @return the value of os_receipt_address.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_receipt_address.update_time
     *
     * @param updateTime the value for os_receipt_address.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}