package com.lanmei.user.dao.model;

import java.util.Date;

public class OsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.user_number
     *
     * @mbggenerated
     */
    private Integer userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.login_password
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.actual_name
     *
     * @mbggenerated
     */
    private String actualName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.age
     *
     * @mbggenerated
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.email_active
     *
     * @mbggenerated
     */
    private Byte emailActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.login_nums
     *
     * @mbggenerated
     */
    private Integer loginNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os_user.head_portrait
     *
     * @mbggenerated
     */
    private byte[] headPortrait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.user_id
     *
     * @return the value of os_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.user_id
     *
     * @param userId the value for os_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.user_number
     *
     * @return the value of os_user.user_number
     *
     * @mbggenerated
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.user_number
     *
     * @param userNumber the value for os_user.user_number
     *
     * @mbggenerated
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.nick_name
     *
     * @return the value of os_user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.nick_name
     *
     * @param nickName the value for os_user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.login_password
     *
     * @return the value of os_user.login_password
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.login_password
     *
     * @param loginPassword the value for os_user.login_password
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.salt
     *
     * @return the value of os_user.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.salt
     *
     * @param salt the value for os_user.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.actual_name
     *
     * @return the value of os_user.actual_name
     *
     * @mbggenerated
     */
    public String getActualName() {
        return actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.actual_name
     *
     * @param actualName the value for os_user.actual_name
     *
     * @mbggenerated
     */
    public void setActualName(String actualName) {
        this.actualName = actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.gender
     *
     * @return the value of os_user.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.gender
     *
     * @param gender the value for os_user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.age
     *
     * @return the value of os_user.age
     *
     * @mbggenerated
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.age
     *
     * @param age the value for os_user.age
     *
     * @mbggenerated
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.status
     *
     * @return the value of os_user.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.status
     *
     * @param status the value for os_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.email
     *
     * @return the value of os_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.email
     *
     * @param email the value for os_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.email_active
     *
     * @return the value of os_user.email_active
     *
     * @mbggenerated
     */
    public Byte getEmailActive() {
        return emailActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.email_active
     *
     * @param emailActive the value for os_user.email_active
     *
     * @mbggenerated
     */
    public void setEmailActive(Byte emailActive) {
        this.emailActive = emailActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.phone_num
     *
     * @return the value of os_user.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.phone_num
     *
     * @param phoneNum the value for os_user.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.register_time
     *
     * @return the value of os_user.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.register_time
     *
     * @param registerTime the value for os_user.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.last_login_time
     *
     * @return the value of os_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.last_login_time
     *
     * @param lastLoginTime the value for os_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.login_nums
     *
     * @return the value of os_user.login_nums
     *
     * @mbggenerated
     */
    public Integer getLoginNums() {
        return loginNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.login_nums
     *
     * @param loginNums the value for os_user.login_nums
     *
     * @mbggenerated
     */
    public void setLoginNums(Integer loginNums) {
        this.loginNums = loginNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os_user.head_portrait
     *
     * @return the value of os_user.head_portrait
     *
     * @mbggenerated
     */
    public byte[] getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os_user.head_portrait
     *
     * @param headPortrait the value for os_user.head_portrait
     *
     * @mbggenerated
     */
    public void setHeadPortrait(byte[] headPortrait) {
        this.headPortrait = headPortrait;
    }
}