package org.lanmei.sysaop.dao.time_measurement.mapper;

import java.util.List;
import org.lanmei.sysaop.dao.time_measurement.model.TimeMeasurement;
import org.springframework.stereotype.Repository;

@Repository
public interface TimeMeasurementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_measurement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer measurementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_measurement
     *
     * @mbg.generated
     */
    int insert(TimeMeasurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_measurement
     *
     * @mbg.generated
     */
    TimeMeasurement selectByPrimaryKey(Integer measurementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_measurement
     *
     * @mbg.generated
     */
    List<TimeMeasurement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_measurement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimeMeasurement record);
    
    TimeMeasurement selectAllByMethod(String method); 
}