package org.lanmei.seckill.dao.model;

import java.util.Date;

import com.fasterxml.jackson.databind.ser.std.SerializableSerializer;

/**
 *	
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table seckill
 *
 * 
 */
public class Seckill extends SerializableSerializer {
    /**
	 * Database Column Remarks: 秒杀ID This field was generated by MyBatis Generator. This field corresponds to the database column seckill.seckill_id
	 * @mbg.generated
	 */
	private Integer seckillId;
	/**
	 * Database Column Remarks: 秒杀名称 This field was generated by MyBatis Generator. This field corresponds to the database column seckill.seckill_name
	 * @mbg.generated
	 */
	private String seckillName;
	/**
	 * Database Column Remarks: 库存数量 This field was generated by MyBatis Generator. This field corresponds to the database column seckill.stock_count
	 * @mbg.generated
	 */
	private Integer stockCount;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column seckill.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * Database Column Remarks: 秒杀时间 This field was generated by MyBatis Generator. This field corresponds to the database column seckill.start_time
	 * @mbg.generated
	 */
	private Date startTime;
	/**
	 * Database Column Remarks: 结束时间 This field was generated by MyBatis Generator. This field corresponds to the database column seckill.finish_time
	 * @mbg.generated
	 */
	
	private Date finishTime;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill.seckill_id
	 * @return  the value of seckill.seckill_id
	 * @mbg.generated
	 */
	public Integer getSeckillId() {
		return seckillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill.seckill_id
	 * @param seckillId  the value for seckill.seckill_id
	 * @mbg.generated
	 */
	public void setSeckillId(Integer seckillId) {
		this.seckillId = seckillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill.seckill_name
	 * @return  the value of seckill.seckill_name
	 * @mbg.generated
	 */
	public String getSeckillName() {
		return seckillName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill.seckill_name
	 * @param seckillName  the value for seckill.seckill_name
	 * @mbg.generated
	 */
	public void setSeckillName(String seckillName) {
		this.seckillName = seckillName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill.stock_count
	 * @return  the value of seckill.stock_count
	 * @mbg.generated
	 */
	public Integer getStockCount() {
		return stockCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill.stock_count
	 * @param stockCount  the value for seckill.stock_count
	 * @mbg.generated
	 */
	public void setStockCount(Integer stockCount) {
		this.stockCount = stockCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill.create_time
	 * @return  the value of seckill.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill.create_time
	 * @param createTime  the value for seckill.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill.start_time
	 * @return  the value of seckill.start_time
	 * @mbg.generated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill.start_time
	 * @param startTime  the value for seckill.start_time
	 * @mbg.generated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seckill.finish_time
	 * @return  the value of seckill.finish_time
	 * @mbg.generated
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seckill.finish_time
	 * @param finishTime  the value for seckill.finish_time
	 * @mbg.generated
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	public Seckill() {
		super();
	}

	public Seckill(Integer seckillId, String seckillName, Integer stockCount, Date createTime, Date startTime,
			Date finishTime) {
		super();
		this.seckillId = seckillId;
		this.seckillName = seckillName;
		this.stockCount = stockCount;
		this.createTime = createTime;
		this.startTime = startTime;
		this.finishTime = finishTime;
	}

	public Seckill(String seckillName, Integer stockCount, Date createTime, Date startTime, Date finishTime) {
		super();
		this.seckillName = seckillName;
		this.stockCount = stockCount;
		this.createTime = createTime;
		this.startTime = startTime;
		this.finishTime = finishTime;
	}
	@Override
	public String toString() {
		
		return ("seckillId = " + seckillId
				+ "  seckillName = " + seckillName
				+ "  stockCount = " + stockCount
				+ "  createTime = " + createTime
				+ "  startTime = " + startTime
				+ "  finishTime = " + finishTime
				);
	}
	
}