package com.lanmei.commodity.dao.mapper;

import com.lanmei.commodity.dao.model.CommodityClassificationAssociation;
import java.util.List;

public interface CommodityClassificationAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification_association
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer associationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification_association
     *
     * @mbggenerated
     */
    int insert(CommodityClassificationAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification_association
     *
     * @mbggenerated
     */
    CommodityClassificationAssociation selectByPrimaryKey(Integer associationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification_association
     *
     * @mbggenerated
     */
    List<CommodityClassificationAssociation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification_association
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityClassificationAssociation record);

    Integer selectCountById(int id);

}