package com.lanmei.commodity.dao.mapper;

import com.lanmei.commodity.dao.model.CommodityImage;
import java.util.List;

public interface CommodityImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int insert(CommodityImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    CommodityImage selectByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    List<CommodityImage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityImage record);
}