package com.lanmei.commodity.dao.mapper;

import com.lanmei.commodity.dao.model.CommodityClassification;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommodityClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification
     *
     * @mbggenerated
     */
    int insert(CommodityClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification
     *
     * @mbggenerated
     */
    CommodityClassification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification
     *
     * @mbggenerated
     */
    List<CommodityClassification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_classification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityClassification record);

    /**
     * 通过父类ＩＤ获取所有子类ＩＤ的数据
     * @param pid
     * @return
     */
    List<CommodityClassification> selectByParentId(Integer pid);
    /**
     * 通过 id 更新 isParent
     * @param id
     * @param isparent
     * @return
     */
    int updateIsParentByPrimaryKey(@Param("id") Integer id ,@Param("isparent") String isparent);
    /**
     * 重命名类目
     * @param id
     * @param name
     * @return
     */
    int updateRename(@Param("id") Integer id ,@Param("name") String name);
    /**
     * 通过ｉd查询IsParent
     */
    Integer selectIsHaveChild( Integer pid );
    /**
     * 通过ｉd 查询pid
     */
    Integer selectPidById( Integer id );
    /**
     * 如果没有子节点，则设置 isparent
     * @param pid
     * @param isparent
     * @return
     */
    Integer updateIsParentNotParent(@Param("pid") Integer pid , @Param("isparent") String isparent);

}