package com.lanmei.commodity.dao.mapper;

import com.lanmei.commodity.dao.model.CommodityReviews;
import java.util.List;

public interface CommodityReviewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_reviews
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer reviewsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_reviews
     *
     * @mbggenerated
     */
    int insert(CommodityReviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_reviews
     *
     * @mbggenerated
     */
    CommodityReviews selectByPrimaryKey(Integer reviewsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_reviews
     *
     * @mbggenerated
     */
    List<CommodityReviews> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_reviews
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityReviews record);
}