package com.lanmei.commodity.dao.mapper;

import com.lanmei.commodity.dao.model.CommodityAttr;
import java.util.List;

public interface CommodityAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_attr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_attr
     *
     * @mbggenerated
     */
    int insert(CommodityAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_attr
     *
     * @mbggenerated
     */
    CommodityAttr selectByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_attr
     *
     * @mbggenerated
     */
    List<CommodityAttr> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityAttr record);

    List<CommodityAttr>  selectByCommodityId(Integer commodityId);
}