package com.lanmei.commodity.dao.mapper;

import com.lanmei.commodity.dao.model.CommoditySku;
import java.util.List;

public interface CommoditySkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sku
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sku
     *
     * @mbggenerated
     */
    int insert(CommoditySku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sku
     *
     * @mbggenerated
     */
    CommoditySku selectByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sku
     *
     * @mbggenerated
     */
    List<CommoditySku> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sku
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommoditySku record);


    List<CommoditySku> selectByCommodityId(Integer commodityId );
}