package org.lanmei.user.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table os_favorites
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OsFavorites {

	/**
	 * Database Column Remarks: 收藏夹ID This field was generated by MyBatis Generator. This field corresponds to the database column os_favorites.favorites_id
	 * @mbg.generated
	 */
	private Integer favoritesId;
	/**
	 * Database Column Remarks: 用户id This field was generated by MyBatis Generator. This field corresponds to the database column os_favorites.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * Database Column Remarks: 商品ID This field was generated by MyBatis Generator. This field corresponds to the database column os_favorites.commodity_id
	 * @mbg.generated
	 */
	private Integer commodityId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_favorites.favorites_id
	 * @return  the value of os_favorites.favorites_id
	 * @mbg.generated
	 */
	public Integer getFavoritesId() {
		return favoritesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_favorites.favorites_id
	 * @param favoritesId  the value for os_favorites.favorites_id
	 * @mbg.generated
	 */
	public void setFavoritesId(Integer favoritesId) {
		this.favoritesId = favoritesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_favorites.user_id
	 * @return  the value of os_favorites.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_favorites.user_id
	 * @param userId  the value for os_favorites.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_favorites.commodity_id
	 * @return  the value of os_favorites.commodity_id
	 * @mbg.generated
	 */
	public Integer getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_favorites.commodity_id
	 * @param commodityId  the value for os_favorites.commodity_id
	 * @mbg.generated
	 */
	public void setCommodityId(Integer commodityId) {
		this.commodityId = commodityId;
	}
}