package org.lanmei.user.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table os_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OsUser {

	/**
	 * Database Column Remarks: 用户ID This field was generated by MyBatis Generator. This field corresponds to the database column os_user.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * Database Column Remarks: 用户编号 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.user_number
	 * @mbg.generated
	 */
	private Integer userNumber;
	/**
	 * Database Column Remarks: 昵称 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.nick_name
	 * @mbg.generated
	 */
	private String nickName;
	/**
	 * Database Column Remarks: 登录密码 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.login_password
	 * @mbg.generated
	 */
	private String loginPassword;
	/**
	 * Database Column Remarks: 真实姓名 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.actual_name
	 * @mbg.generated
	 */
	private String actualName;
	/**
	 * Database Column Remarks: 性别 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.gender
	 * @mbg.generated
	 */
	private String gender;
	/**
	 * Database Column Remarks: 年龄 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.age
	 * @mbg.generated
	 */
	private Byte age;
	/**
	 * Database Column Remarks: 状态 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 电子邮箱 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * Database Column Remarks: 邮箱是否激活 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.email_active
	 * @mbg.generated
	 */
	private Byte emailActive;
	/**
	 * Database Column Remarks: 电话号码 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.phone_num
	 * @mbg.generated
	 */
	private String phoneNum;
	/**
	 * Database Column Remarks: 注册时间 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.register_time
	 * @mbg.generated
	 */
	private Date registerTime;
	/**
	 * Database Column Remarks: 最后登录时间 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.last_login_time
	 * @mbg.generated
	 */
	private Date lastLoginTime;
	/**
	 * Database Column Remarks: 登录次数 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.login_nums
	 * @mbg.generated
	 */
	private Integer loginNums;
	/**
	 * Database Column Remarks: 头像 This field was generated by MyBatis Generator. This field corresponds to the database column os_user.head_portrait
	 * @mbg.generated
	 */
	private byte[] headPortrait;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.user_id
	 * @return  the value of os_user.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.user_id
	 * @param userId  the value for os_user.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.user_number
	 * @return  the value of os_user.user_number
	 * @mbg.generated
	 */
	public Integer getUserNumber() {
		return userNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.user_number
	 * @param userNumber  the value for os_user.user_number
	 * @mbg.generated
	 */
	public void setUserNumber(Integer userNumber) {
		this.userNumber = userNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.nick_name
	 * @return  the value of os_user.nick_name
	 * @mbg.generated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.nick_name
	 * @param nickName  the value for os_user.nick_name
	 * @mbg.generated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.login_password
	 * @return  the value of os_user.login_password
	 * @mbg.generated
	 */
	public String getLoginPassword() {
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.login_password
	 * @param loginPassword  the value for os_user.login_password
	 * @mbg.generated
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.actual_name
	 * @return  the value of os_user.actual_name
	 * @mbg.generated
	 */
	public String getActualName() {
		return actualName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.actual_name
	 * @param actualName  the value for os_user.actual_name
	 * @mbg.generated
	 */
	public void setActualName(String actualName) {
		this.actualName = actualName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.gender
	 * @return  the value of os_user.gender
	 * @mbg.generated
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.gender
	 * @param gender  the value for os_user.gender
	 * @mbg.generated
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.age
	 * @return  the value of os_user.age
	 * @mbg.generated
	 */
	public Byte getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.age
	 * @param age  the value for os_user.age
	 * @mbg.generated
	 */
	public void setAge(Byte age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.status
	 * @return  the value of os_user.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.status
	 * @param status  the value for os_user.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.email
	 * @return  the value of os_user.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.email
	 * @param email  the value for os_user.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.email_active
	 * @return  the value of os_user.email_active
	 * @mbg.generated
	 */
	public Byte getEmailActive() {
		return emailActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.email_active
	 * @param emailActive  the value for os_user.email_active
	 * @mbg.generated
	 */
	public void setEmailActive(Byte emailActive) {
		this.emailActive = emailActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.phone_num
	 * @return  the value of os_user.phone_num
	 * @mbg.generated
	 */
	public String getPhoneNum() {
		return phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.phone_num
	 * @param phoneNum  the value for os_user.phone_num
	 * @mbg.generated
	 */
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.register_time
	 * @return  the value of os_user.register_time
	 * @mbg.generated
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.register_time
	 * @param registerTime  the value for os_user.register_time
	 * @mbg.generated
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.last_login_time
	 * @return  the value of os_user.last_login_time
	 * @mbg.generated
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.last_login_time
	 * @param lastLoginTime  the value for os_user.last_login_time
	 * @mbg.generated
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.login_nums
	 * @return  the value of os_user.login_nums
	 * @mbg.generated
	 */
	public Integer getLoginNums() {
		return loginNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.login_nums
	 * @param loginNums  the value for os_user.login_nums
	 * @mbg.generated
	 */
	public void setLoginNums(Integer loginNums) {
		this.loginNums = loginNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column os_user.head_portrait
	 * @return  the value of os_user.head_portrait
	 * @mbg.generated
	 */
	public byte[] getHeadPortrait() {
		return headPortrait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column os_user.head_portrait
	 * @param headPortrait  the value for os_user.head_portrait
	 * @mbg.generated
	 */
	public void setHeadPortrait(byte[] headPortrait) {
		this.headPortrait = headPortrait;
	}
	
	
	public String toString() {

		return  "OsUser属性值：+\r\n"
				+ "  UserId = " + this.getUserId() 
				+ "  UserNumber = " + this.getUserNumber() ;
	}
}