package org.lanmei.sysaop.dao.syslog.mapper;

import java.util.List;

import org.lanmei.sysaop.dao.syslog.model.SystemLog;
import org.springframework.stereotype.Repository;


@Repository
public interface SystemLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_log
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_log
	 * @mbg.generated
	 */
	int insert(SystemLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_log
	 * @mbg.generated
	 */
	SystemLog selectByPrimaryKey(Integer logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_log
	 * @mbg.generated
	 */
	List<SystemLog> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_log
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SystemLog record);
}