package com.lanmei.seckill.dao.model;

import java.util.Date;

public class Seckill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_id
     *
     * @mbggenerated
     */
    private Integer seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_name
     *
     * @mbggenerated
     */
    private String seckillName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.stock_count
     *
     * @mbggenerated
     */
    private Integer stockCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.finish_time
     *
     * @mbggenerated
     */
    private Date finishTime;

    public Seckill(Integer seckillId, String seckillName, Integer stockCount, Date createTime, Date startTime,
                   Date finishTime) {
        super();
        this.seckillId = seckillId;
        this.seckillName = seckillName;
        this.stockCount = stockCount;
        this.createTime = createTime;
        this.startTime = startTime;
        this.finishTime = finishTime;
    }

    public Seckill(String seckillName, Integer stockCount, Date createTime, Date startTime, Date finishTime) {
        super();
        this.seckillName = seckillName;
        this.stockCount = stockCount;
        this.createTime = createTime;
        this.startTime = startTime;
        this.finishTime = finishTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_id
     *
     * @return the value of seckill.seckill_id
     *
     * @mbggenerated
     */
    public Integer getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_id
     *
     * @param seckillId the value for seckill.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(Integer seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_name
     *
     * @return the value of seckill.seckill_name
     *
     * @mbggenerated
     */
    public String getSeckillName() {
        return seckillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_name
     *
     * @param seckillName the value for seckill.seckill_name
     *
     * @mbggenerated
     */
    public void setSeckillName(String seckillName) {
        this.seckillName = seckillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.stock_count
     *
     * @return the value of seckill.stock_count
     *
     * @mbggenerated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.stock_count
     *
     * @param stockCount the value for seckill.stock_count
     *
     * @mbggenerated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.create_time
     *
     * @return the value of seckill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.create_time
     *
     * @param createTime the value for seckill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.start_time
     *
     * @return the value of seckill.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.start_time
     *
     * @param startTime the value for seckill.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.finish_time
     *
     * @return the value of seckill.finish_time
     *
     * @mbggenerated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.finish_time
     *
     * @param finishTime the value for seckill.finish_time
     *
     * @mbggenerated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }



    @Override
    public String toString() {

        return ("seckillId = " + seckillId
                + "  seckillName = " + seckillName
                + "  stockCount = " + stockCount
                + "  createTime = " + createTime
                + "  startTime = " + startTime
                + "  finishTime = " + finishTime
        );
    }

}