package com.lanmei.seckill.dao.model;

import java.util.Date;

public class SeckillSuccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_success.seckill_id
     *
     * @mbggenerated
     */
    private Integer seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_success.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_success.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_success.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    public SeckillSuccess(Integer seckillId, Integer userId, String state, Date createTime) {
        super();
        this.seckillId = seckillId;
        this.userId = userId;
        this.state = state;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_success.seckill_id
     *
     * @return the value of seckill_success.seckill_id
     *
     * @mbggenerated
     */
    public Integer getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_success.seckill_id
     *
     * @param seckillId the value for seckill_success.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(Integer seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_success.user_id
     *
     * @return the value of seckill_success.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_success.user_id
     *
     * @param userId the value for seckill_success.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_success.state
     *
     * @return the value of seckill_success.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_success.state
     *
     * @param state the value for seckill_success.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_success.create_time
     *
     * @return the value of seckill_success.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_success.create_time
     *
     * @param createTime the value for seckill_success.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}