package com.lanmei.seckill.dao.mapper;

import com.lanmei.seckill.dao.model.SeckillSuccess;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SeckillSuccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_success
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("seckillId") Integer seckillId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_success
     *
     * @mbggenerated
     */
    int insert(SeckillSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_success
     *
     * @mbggenerated
     */
    SeckillSuccess selectByPrimaryKey(@Param("seckillId") Integer seckillId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_success
     *
     * @mbggenerated
     */
    List<SeckillSuccess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_success
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SeckillSuccess record);

    int insertRecord(SeckillSuccess record);
}