package org.lanmei.user.dao.mapper;

import java.util.List;
import org.lanmei.user.dao.model.OsReceiptAddress;

public interface OsReceiptAddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table os_receipt_address
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer receiptAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table os_receipt_address
	 * @mbg.generated
	 */
	int insert(OsReceiptAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table os_receipt_address
	 * @mbg.generated
	 */
	OsReceiptAddress selectByPrimaryKey(Integer receiptAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table os_receipt_address
	 * @mbg.generated
	 */
	List<OsReceiptAddress> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table os_receipt_address
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OsReceiptAddress record);
}