package com.lanmei.admin.dao.mapper;

import com.lanmei.admin.dao.model.CmsAdmin;
import java.util.List;

public interface CmsAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_admin
     *
     * @mbggenerated
     */
    int insert(CmsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_admin
     *
     * @mbggenerated
     */
    CmsAdmin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_admin
     *
     * @mbggenerated
     */
    List<CmsAdmin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsAdmin record);

    int insertNewAdmin(CmsAdmin record);

    CmsAdmin selectByLoginJobnum(String loginJobnum);

    int selectCount();

}