package org.lanmei.commodity.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commodity_reviews
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CommodityReviews {

	/**
	 * Database Column Remarks: 商品ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.reviews_id
	 * @mbg.generated
	 */
	private Integer reviewsId;
	/**
	 * Database Column Remarks: 商品ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.commodity_id
	 * @mbg.generated
	 */
	private Integer commodityId;
	/**
	 * Database Column Remarks: 评价等级0-５颗星 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.grade
	 * @mbg.generated
	 */
	private Byte grade;
	/**
	 * Database Column Remarks: 0/1,是否是有图评价 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.is_have_image
	 * @mbg.generated
	 */
	private Byte isHaveImage;
	/**
	 * Database Column Remarks: 0/1,是否是追加评价 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.is_additional_reviews
	 * @mbg.generated
	 */
	private Byte isAdditionalReviews;
	/**
	 * Database Column Remarks: 评价人，手机号 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.reviews_by
	 * @mbg.generated
	 */
	private String reviewsBy;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.reviews_time
	 * @mbg.generated
	 */
	private Date reviewsTime;
	/**
	 * Database Column Remarks: 评价内容 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_reviews.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.reviews_id
	 * @return  the value of commodity_reviews.reviews_id
	 * @mbg.generated
	 */
	public Integer getReviewsId() {
		return reviewsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.reviews_id
	 * @param reviewsId  the value for commodity_reviews.reviews_id
	 * @mbg.generated
	 */
	public void setReviewsId(Integer reviewsId) {
		this.reviewsId = reviewsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.commodity_id
	 * @return  the value of commodity_reviews.commodity_id
	 * @mbg.generated
	 */
	public Integer getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.commodity_id
	 * @param commodityId  the value for commodity_reviews.commodity_id
	 * @mbg.generated
	 */
	public void setCommodityId(Integer commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.grade
	 * @return  the value of commodity_reviews.grade
	 * @mbg.generated
	 */
	public Byte getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.grade
	 * @param grade  the value for commodity_reviews.grade
	 * @mbg.generated
	 */
	public void setGrade(Byte grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.is_have_image
	 * @return  the value of commodity_reviews.is_have_image
	 * @mbg.generated
	 */
	public Byte getIsHaveImage() {
		return isHaveImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.is_have_image
	 * @param isHaveImage  the value for commodity_reviews.is_have_image
	 * @mbg.generated
	 */
	public void setIsHaveImage(Byte isHaveImage) {
		this.isHaveImage = isHaveImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.is_additional_reviews
	 * @return  the value of commodity_reviews.is_additional_reviews
	 * @mbg.generated
	 */
	public Byte getIsAdditionalReviews() {
		return isAdditionalReviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.is_additional_reviews
	 * @param isAdditionalReviews  the value for commodity_reviews.is_additional_reviews
	 * @mbg.generated
	 */
	public void setIsAdditionalReviews(Byte isAdditionalReviews) {
		this.isAdditionalReviews = isAdditionalReviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.reviews_by
	 * @return  the value of commodity_reviews.reviews_by
	 * @mbg.generated
	 */
	public String getReviewsBy() {
		return reviewsBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.reviews_by
	 * @param reviewsBy  the value for commodity_reviews.reviews_by
	 * @mbg.generated
	 */
	public void setReviewsBy(String reviewsBy) {
		this.reviewsBy = reviewsBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.reviews_time
	 * @return  the value of commodity_reviews.reviews_time
	 * @mbg.generated
	 */
	public Date getReviewsTime() {
		return reviewsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.reviews_time
	 * @param reviewsTime  the value for commodity_reviews.reviews_time
	 * @mbg.generated
	 */
	public void setReviewsTime(Date reviewsTime) {
		this.reviewsTime = reviewsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_reviews.content
	 * @return  the value of commodity_reviews.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_reviews.content
	 * @param content  the value for commodity_reviews.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content;
	}
}