package org.lanmei.commodity.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commodity_classification
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CommodityClassification {

	/**
	 * Database Column Remarks: 分类ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 父分类ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification.pid
	 * @mbg.generated
	 */
	private Integer pid;
	/**
	 * Database Column Remarks: 分类名称 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 是否是父分类，是父分类说明有子类 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification.isParent
	 * @mbg.generated
	 */
	private String isparent;
	/**
	 * Database Column Remarks: 创建人 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification.create_by
	 * @mbg.generated
	 */
	private String createBy;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * Database Column Remarks: 备注 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification.remarks
	 * @mbg.generated
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification.id
	 * @return  the value of commodity_classification.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification.id
	 * @param id  the value for commodity_classification.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification.pid
	 * @return  the value of commodity_classification.pid
	 * @mbg.generated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification.pid
	 * @param pid  the value for commodity_classification.pid
	 * @mbg.generated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification.name
	 * @return  the value of commodity_classification.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification.name
	 * @param name  the value for commodity_classification.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification.isParent
	 * @return  the value of commodity_classification.isParent
	 * @mbg.generated
	 */
	public String getIsparent() {
		return isparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification.isParent
	 * @param isparent  the value for commodity_classification.isParent
	 * @mbg.generated
	 */
	public void setIsparent(String isparent) {
		this.isparent = isparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification.create_by
	 * @return  the value of commodity_classification.create_by
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification.create_by
	 * @param createBy  the value for commodity_classification.create_by
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification.create_time
	 * @return  the value of commodity_classification.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification.create_time
	 * @param createTime  the value for commodity_classification.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification.remarks
	 * @return  the value of commodity_classification.remarks
	 * @mbg.generated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification.remarks
	 * @param remarks  the value for commodity_classification.remarks
	 * @mbg.generated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public CommodityClassification() {
		super();
	}

	public CommodityClassification(Integer pid, String name, String isparent, String createBy, Date createTime) {
		super();
		this.pid = pid;
		this.name = name;
		this.isparent = isparent;
		this.createBy = createBy;
		this.createTime = createTime;
	}
}