package org.lanmei.commodity.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commodity_sku_collect
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CommoditySkuCollect {

	/**
	 * Database Column Remarks: sku 集合 ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_sku_collect.sku_collect_id
	 * @mbg.generated
	 */
	private Integer skuCollectId;
	/**
	 * Database Column Remarks: 商品ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_sku_collect.commodity_id
	 * @mbg.generated
	 */
	private Integer commodityId;
	/**
	 * Database Column Remarks: 价格 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_sku_collect.price
	 * @mbg.generated
	 */
	private Double price;
	/**
	 * Database Column Remarks: 库存 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_sku_collect.stock
	 * @mbg.generated
	 */
	private Integer stock;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_sku_collect.sku_collect_id
	 * @return  the value of commodity_sku_collect.sku_collect_id
	 * @mbg.generated
	 */
	public Integer getSkuCollectId() {
		return skuCollectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_sku_collect.sku_collect_id
	 * @param skuCollectId  the value for commodity_sku_collect.sku_collect_id
	 * @mbg.generated
	 */
	public void setSkuCollectId(Integer skuCollectId) {
		this.skuCollectId = skuCollectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_sku_collect.commodity_id
	 * @return  the value of commodity_sku_collect.commodity_id
	 * @mbg.generated
	 */
	public Integer getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_sku_collect.commodity_id
	 * @param commodityId  the value for commodity_sku_collect.commodity_id
	 * @mbg.generated
	 */
	public void setCommodityId(Integer commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_sku_collect.price
	 * @return  the value of commodity_sku_collect.price
	 * @mbg.generated
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_sku_collect.price
	 * @param price  the value for commodity_sku_collect.price
	 * @mbg.generated
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_sku_collect.stock
	 * @return  the value of commodity_sku_collect.stock
	 * @mbg.generated
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_sku_collect.stock
	 * @param stock  the value for commodity_sku_collect.stock
	 * @mbg.generated
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}
}