package org.lanmei.commodity.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commodity
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Commodity {

	/**
	 * Database Column Remarks: 商品ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity.commodity_id
	 * @mbg.generated
	 */
	private Integer commodityId;
	/**
	 * Database Column Remarks: 商品名称 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 显示标题 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * Database Column Remarks: 参考价格 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.reference_price
	 * @mbg.generated
	 */
	private Float referencePrice;
	/**
	 * Database Column Remarks: 活动价格 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.activity_price
	 * @mbg.generated
	 */
	private Float activityPrice;
	/**
	 * Database Column Remarks: 商品简介 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * Database Column Remarks: 创建人 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.create_by
	 * @mbg.generated
	 */
	private String createBy;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * Database Column Remarks: 上架时间 This field was generated by MyBatis Generator. This field corresponds to the database column commodity.put_on_sale_time
	 * @mbg.generated
	 */
	private Date putOnSaleTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.commodity_id
	 * @return  the value of commodity.commodity_id
	 * @mbg.generated
	 */
	public Integer getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.commodity_id
	 * @param commodityId  the value for commodity.commodity_id
	 * @mbg.generated
	 */
	public void setCommodityId(Integer commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.name
	 * @return  the value of commodity.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.name
	 * @param name  the value for commodity.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.title
	 * @return  the value of commodity.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.title
	 * @param title  the value for commodity.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.reference_price
	 * @return  the value of commodity.reference_price
	 * @mbg.generated
	 */
	public Float getReferencePrice() {
		return referencePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.reference_price
	 * @param referencePrice  the value for commodity.reference_price
	 * @mbg.generated
	 */
	public void setReferencePrice(Float referencePrice) {
		this.referencePrice = referencePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.activity_price
	 * @return  the value of commodity.activity_price
	 * @mbg.generated
	 */
	public Float getActivityPrice() {
		return activityPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.activity_price
	 * @param activityPrice  the value for commodity.activity_price
	 * @mbg.generated
	 */
	public void setActivityPrice(Float activityPrice) {
		this.activityPrice = activityPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.description
	 * @return  the value of commodity.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.description
	 * @param description  the value for commodity.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.create_by
	 * @return  the value of commodity.create_by
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.create_by
	 * @param createBy  the value for commodity.create_by
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.create_time
	 * @return  the value of commodity.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.create_time
	 * @param createTime  the value for commodity.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.put_on_sale_time
	 * @return  the value of commodity.put_on_sale_time
	 * @mbg.generated
	 */
	public Date getPutOnSaleTime() {
		return putOnSaleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.put_on_sale_time
	 * @param putOnSaleTime  the value for commodity.put_on_sale_time
	 * @mbg.generated
	 */
	public void setPutOnSaleTime(Date putOnSaleTime) {
		this.putOnSaleTime = putOnSaleTime;
	}
}