package org.lanmei.commodity.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commodity_classification_association
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CommodityClassificationAssociation {

	/**
	 * Database Column Remarks: 商品分类ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification_association.association_id
	 * @mbg.generated
	 */
	private Integer associationId;
	/**
	 * Database Column Remarks: 商品ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification_association.commodity_id
	 * @mbg.generated
	 */
	private Integer commodityId;
	/**
	 * Database Column Remarks: 分类ID This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification_association.classification_id
	 * @mbg.generated
	 */
	private Integer classificationId;
	/**
	 * Database Column Remarks: 创建人 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification_association.create_by
	 * @mbg.generated
	 */
	private String createBy;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column commodity_classification_association.create_time
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification_association.association_id
	 * @return  the value of commodity_classification_association.association_id
	 * @mbg.generated
	 */
	public Integer getAssociationId() {
		return associationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification_association.association_id
	 * @param associationId  the value for commodity_classification_association.association_id
	 * @mbg.generated
	 */
	public void setAssociationId(Integer associationId) {
		this.associationId = associationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification_association.commodity_id
	 * @return  the value of commodity_classification_association.commodity_id
	 * @mbg.generated
	 */
	public Integer getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification_association.commodity_id
	 * @param commodityId  the value for commodity_classification_association.commodity_id
	 * @mbg.generated
	 */
	public void setCommodityId(Integer commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification_association.classification_id
	 * @return  the value of commodity_classification_association.classification_id
	 * @mbg.generated
	 */
	public Integer getClassificationId() {
		return classificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification_association.classification_id
	 * @param classificationId  the value for commodity_classification_association.classification_id
	 * @mbg.generated
	 */
	public void setClassificationId(Integer classificationId) {
		this.classificationId = classificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification_association.create_by
	 * @return  the value of commodity_classification_association.create_by
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification_association.create_by
	 * @param createBy  the value for commodity_classification_association.create_by
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity_classification_association.create_time
	 * @return  the value of commodity_classification_association.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity_classification_association.create_time
	 * @param createTime  the value for commodity_classification_association.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}