package org.lanmei.commodity.dao.mapper;

import java.util.List;
import org.lanmei.commodity.dao.model.CommodityClassification;
import org.springframework.stereotype.Repository;

@Repository
public interface CommodityClassificationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	int insert(CommodityClassification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	CommodityClassification selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	List<CommodityClassification> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CommodityClassification record);

	/*自定义*/
    /**
     * 通过父类ＩＤ获取所有子类ＩＤ的数据
     * @param parentId
     * @return
     */
    List<CommodityClassification> selectByＰarentId(Integer pid);
}