package org.lanmei.commodity.dao.mapper;

import java.util.List;
import org.lanmei.commodity.dao.model.CommodityAttr;
import org.springframework.stereotype.Repository;

@Repository
public interface CommodityAttrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_attr
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer attrId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_attr
	 * @mbg.generated
	 */
	int insert(CommodityAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_attr
	 * @mbg.generated
	 */
	CommodityAttr selectByPrimaryKey(Integer attrId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_attr
	 * @mbg.generated
	 */
	List<CommodityAttr> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_attr
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CommodityAttr record);
	/**
	 * 通过商品id获取数据
	 * @param commodity
	 * @return
	 */
	List<CommodityAttr> selectByCommodityId(Integer commodity);
}