package org.lanmei.commodity.dao.mapper;

import java.util.List;
import org.lanmei.commodity.dao.model.CommodityReviews;
import org.springframework.stereotype.Repository;

@Repository
public interface CommodityReviewsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_reviews
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer reviewsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_reviews
	 * @mbg.generated
	 */
	int insert(CommodityReviews record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_reviews
	 * @mbg.generated
	 */
	CommodityReviews selectByPrimaryKey(Integer reviewsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_reviews
	 * @mbg.generated
	 */
	List<CommodityReviews> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_reviews
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CommodityReviews record);
}