package org.lanmei.commodity.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.lanmei.commodity.dao.model.CommodityClassification;
import org.springframework.stereotype.Repository;

@Repository
public interface CommodityClassificationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	int insert(CommodityClassification record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	CommodityClassification selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	List<CommodityClassification> selectAll();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity_classification
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CommodityClassification record);
	/*自定义*/
    /**
     * 通过父类ＩＤ获取所有子类ＩＤ的数据
     * @param parentId
     * @return
     */
    List<CommodityClassification> selectByＰarentId(Integer pid);
    /**
     * 通过 id 更新 isParent
     * @param id
     * @param isparent
     * @return
     */
    int updateIsParentByPrimaryKey(@Param("id") Integer id ,@Param("isparent") String isparent);
    /**
     * 重命名类目
     * @param id
     * @param name
     * @return
     */
    int updateRename(@Param("id") Integer id ,@Param("name") String name);
    /**
     * 通过ｉd查询IsParent
     */
    Integer selectIsHaveChild( Integer pid );
    /**
     * 通过ｉd 查询pid
     */
    Integer selectPidById( Integer id );
    /**
     * 如果没有子节点，则设置 isparent
     * @param pid
     * @param isparent
     * @return
     */
    Integer updateIsParentNotParent(@Param("pid") Integer pid ,@Param("isparent") String isparent);
}