package org.lanmei.admin.dao.mapper;

import java.util.List;
import org.lanmei.admin.dao.model.CmsAdmin;

public interface CmsAdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer adminId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbg.generated
	 */
	int insert(CmsAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbg.generated
	 */
	CmsAdmin selectByPrimaryKey(Integer adminId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbg.generated
	 */
	List<CmsAdmin> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CmsAdmin record);
}