package org.lanmei.admin.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.lanmei.admin.dao.model.CmsAdminLogin;

public interface CmsAdminLoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin_login
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin_login
	 * @mbg.generated
	 */
	int insert(CmsAdminLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin_login
	 * @mbg.generated
	 */
	CmsAdminLogin selectByPrimaryKey(Integer loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin_login
	 * @mbg.generated
	 */
	List<CmsAdminLogin> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin_login
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CmsAdminLogin record);

	int insertByAdminId(@Param("adminId") Integer adminId,@Param("adminLogin") CmsAdminLogin adminLogin);
}