package com.lanmei.user.dao.mapper;

import com.lanmei.user.dao.model.OsFavorites;
import java.util.List;

public interface OsFavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_favorites
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer favoritesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_favorites
     *
     * @mbggenerated
     */
    int insert(OsFavorites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_favorites
     *
     * @mbggenerated
     */
    OsFavorites selectByPrimaryKey(Integer favoritesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_favorites
     *
     * @mbggenerated
     */
    List<OsFavorites> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_favorites
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OsFavorites record);
}