package com.lanmei.user.dao.mapper;

import com.lanmei.user.dao.model.OsReceiptAddress;
import java.util.List;

public interface OsReceiptAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_receipt_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer receiptAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_receipt_address
     *
     * @mbggenerated
     */
    int insert(OsReceiptAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_receipt_address
     *
     * @mbggenerated
     */
    OsReceiptAddress selectByPrimaryKey(Integer receiptAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_receipt_address
     *
     * @mbggenerated
     */
    List<OsReceiptAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_receipt_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OsReceiptAddress record);
}