package com.lanmei.user.dao.mapper;

import com.lanmei.user.dao.model.OsUserLogin;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OsUserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user_login
     *
     * @mbggenerated
     */
    int insert(OsUserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user_login
     *
     * @mbggenerated
     */
    OsUserLogin selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user_login
     *
     * @mbggenerated
     */
    List<OsUserLogin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OsUserLogin record);

    /*通过userId更新登录日志*/
    int updateByUserId(@Param("userId") Integer userId,@Param("userLogin") OsUserLogin  userLogin);
    /*通过userId插入登录日志*/
    int insertByUserId(@Param("userId") Integer userId,@Param("userLogin") OsUserLogin  userLogin);
    /*通过userId获取登录日志*/
    List<OsUserLogin> selectByUserId(Integer userId);

}