package com.lanmei.commodity.dao.model;

public class CommoditySku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku.sku_id
     *
     * @mbggenerated
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku.sku_collect_id
     *
     * @mbggenerated
     */
    private Integer skuCollectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku.attr
     *
     * @mbggenerated
     */
    private String attr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku.sku_id
     *
     * @return the value of commodity_sku.sku_id
     *
     * @mbggenerated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku.sku_id
     *
     * @param skuId the value for commodity_sku.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku.sku_collect_id
     *
     * @return the value of commodity_sku.sku_collect_id
     *
     * @mbggenerated
     */
    public Integer getSkuCollectId() {
        return skuCollectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku.sku_collect_id
     *
     * @param skuCollectId the value for commodity_sku.sku_collect_id
     *
     * @mbggenerated
     */
    public void setSkuCollectId(Integer skuCollectId) {
        this.skuCollectId = skuCollectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku.commodity_id
     *
     * @return the value of commodity_sku.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku.commodity_id
     *
     * @param commodityId the value for commodity_sku.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku.name
     *
     * @return the value of commodity_sku.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku.name
     *
     * @param name the value for commodity_sku.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku.attr
     *
     * @return the value of commodity_sku.attr
     *
     * @mbggenerated
     */
    public String getAttr() {
        return attr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku.attr
     *
     * @param attr the value for commodity_sku.attr
     *
     * @mbggenerated
     */
    public void setAttr(String attr) {
        this.attr = attr;
    }
}