package com.lanmei.commodity.dao.model;

import java.util.Date;

public class Commodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.put_on_sale_time
     *
     * @mbggenerated
     */
    private Date putOnSaleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.put_off_sale_time
     *
     * @mbggenerated
     */
    private Date putOffSaleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.sale_state
     *
     * @mbggenerated
     */
    private Byte saleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_id
     *
     * @return the value of commodity.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_id
     *
     * @param commodityId the value for commodity.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.category_id
     *
     * @return the value of commodity.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.category_id
     *
     * @param categoryId the value for commodity.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.brand
     *
     * @return the value of commodity.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.brand
     *
     * @param brand the value for commodity.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.title
     *
     * @return the value of commodity.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.title
     *
     * @param title the value for commodity.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.create_by
     *
     * @return the value of commodity.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.create_by
     *
     * @param createBy the value for commodity.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.create_time
     *
     * @return the value of commodity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.create_time
     *
     * @param createTime the value for commodity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.put_on_sale_time
     *
     * @return the value of commodity.put_on_sale_time
     *
     * @mbggenerated
     */
    public Date getPutOnSaleTime() {
        return putOnSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.put_on_sale_time
     *
     * @param putOnSaleTime the value for commodity.put_on_sale_time
     *
     * @mbggenerated
     */
    public void setPutOnSaleTime(Date putOnSaleTime) {
        this.putOnSaleTime = putOnSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.put_off_sale_time
     *
     * @return the value of commodity.put_off_sale_time
     *
     * @mbggenerated
     */
    public Date getPutOffSaleTime() {
        return putOffSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.put_off_sale_time
     *
     * @param putOffSaleTime the value for commodity.put_off_sale_time
     *
     * @mbggenerated
     */
    public void setPutOffSaleTime(Date putOffSaleTime) {
        this.putOffSaleTime = putOffSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.sale_state
     *
     * @return the value of commodity.sale_state
     *
     * @mbggenerated
     */
    public Byte getSaleState() {
        return saleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.sale_state
     *
     * @param saleState the value for commodity.sale_state
     *
     * @mbggenerated
     */
    public void setSaleState(Byte saleState) {
        this.saleState = saleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.description
     *
     * @return the value of commodity.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.description
     *
     * @param description the value for commodity.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}