package com.lanmei.commodity.dao.model;

import java.util.Date;

public class CommodityClassification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification.isParent
     *
     * @mbggenerated
     */
    private String isparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    public CommodityClassification(Integer id, Integer pid) {
        super();
        this.id = id;
        this.pid = pid;
    }

    public CommodityClassification() {
        super();
    }

    public CommodityClassification(Integer pid, String name, String isparent, String createBy, Date createTime) {
        super();
        this.pid = pid;
        this.name = name;
        this.isparent = isparent;
        this.createBy = createBy;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification.id
     *
     * @return the value of commodity_classification.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification.id
     *
     * @param id the value for commodity_classification.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification.pid
     *
     * @return the value of commodity_classification.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification.pid
     *
     * @param pid the value for commodity_classification.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification.name
     *
     * @return the value of commodity_classification.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification.name
     *
     * @param name the value for commodity_classification.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification.isParent
     *
     * @return the value of commodity_classification.isParent
     *
     * @mbggenerated
     */
    public String getIsparent() {
        return isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification.isParent
     *
     * @param isparent the value for commodity_classification.isParent
     *
     * @mbggenerated
     */
    public void setIsparent(String isparent) {
        this.isparent = isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification.create_by
     *
     * @return the value of commodity_classification.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification.create_by
     *
     * @param createBy the value for commodity_classification.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification.create_time
     *
     * @return the value of commodity_classification.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification.create_time
     *
     * @param createTime the value for commodity_classification.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification.remarks
     *
     * @return the value of commodity_classification.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification.remarks
     *
     * @param remarks the value for commodity_classification.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}