package com.lanmei.commodity.dao.model;

public class CommoditySkuCollect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku_collect.sku_collect_id
     *
     * @mbggenerated
     */
    private Integer skuCollectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku_collect.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku_collect.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sku_collect.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku_collect.sku_collect_id
     *
     * @return the value of commodity_sku_collect.sku_collect_id
     *
     * @mbggenerated
     */
    public Integer getSkuCollectId() {
        return skuCollectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku_collect.sku_collect_id
     *
     * @param skuCollectId the value for commodity_sku_collect.sku_collect_id
     *
     * @mbggenerated
     */
    public void setSkuCollectId(Integer skuCollectId) {
        this.skuCollectId = skuCollectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku_collect.commodity_id
     *
     * @return the value of commodity_sku_collect.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku_collect.commodity_id
     *
     * @param commodityId the value for commodity_sku_collect.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku_collect.price
     *
     * @return the value of commodity_sku_collect.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku_collect.price
     *
     * @param price the value for commodity_sku_collect.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sku_collect.stock
     *
     * @return the value of commodity_sku_collect.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sku_collect.stock
     *
     * @param stock the value for commodity_sku_collect.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}