package com.lanmei.commodity.dao.model;

import java.util.Date;

public class CommodityClassificationAssociation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification_association.association_id
     *
     * @mbggenerated
     */
    private Integer associationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification_association.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification_association.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification_association.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_classification_association.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification_association.association_id
     *
     * @return the value of commodity_classification_association.association_id
     *
     * @mbggenerated
     */
    public Integer getAssociationId() {
        return associationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification_association.association_id
     *
     * @param associationId the value for commodity_classification_association.association_id
     *
     * @mbggenerated
     */
    public void setAssociationId(Integer associationId) {
        this.associationId = associationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification_association.commodity_id
     *
     * @return the value of commodity_classification_association.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification_association.commodity_id
     *
     * @param commodityId the value for commodity_classification_association.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification_association.id
     *
     * @return the value of commodity_classification_association.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification_association.id
     *
     * @param id the value for commodity_classification_association.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification_association.create_by
     *
     * @return the value of commodity_classification_association.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification_association.create_by
     *
     * @param createBy the value for commodity_classification_association.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_classification_association.create_time
     *
     * @return the value of commodity_classification_association.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_classification_association.create_time
     *
     * @param createTime the value for commodity_classification_association.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}