package com.lanmei.commodity.dao.model;

import java.util.Date;

public class CommodityReviews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.reviews_id
     *
     * @mbggenerated
     */
    private Integer reviewsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.grade
     *
     * @mbggenerated
     */
    private Byte grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.is_have_image
     *
     * @mbggenerated
     */
    private Byte isHaveImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.is_additional_reviews
     *
     * @mbggenerated
     */
    private Byte isAdditionalReviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.reviews_by
     *
     * @mbggenerated
     */
    private String reviewsBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.reviews_time
     *
     * @mbggenerated
     */
    private Date reviewsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_reviews.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.reviews_id
     *
     * @return the value of commodity_reviews.reviews_id
     *
     * @mbggenerated
     */
    public Integer getReviewsId() {
        return reviewsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.reviews_id
     *
     * @param reviewsId the value for commodity_reviews.reviews_id
     *
     * @mbggenerated
     */
    public void setReviewsId(Integer reviewsId) {
        this.reviewsId = reviewsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.commodity_id
     *
     * @return the value of commodity_reviews.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.commodity_id
     *
     * @param commodityId the value for commodity_reviews.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.grade
     *
     * @return the value of commodity_reviews.grade
     *
     * @mbggenerated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.grade
     *
     * @param grade the value for commodity_reviews.grade
     *
     * @mbggenerated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.is_have_image
     *
     * @return the value of commodity_reviews.is_have_image
     *
     * @mbggenerated
     */
    public Byte getIsHaveImage() {
        return isHaveImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.is_have_image
     *
     * @param isHaveImage the value for commodity_reviews.is_have_image
     *
     * @mbggenerated
     */
    public void setIsHaveImage(Byte isHaveImage) {
        this.isHaveImage = isHaveImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.is_additional_reviews
     *
     * @return the value of commodity_reviews.is_additional_reviews
     *
     * @mbggenerated
     */
    public Byte getIsAdditionalReviews() {
        return isAdditionalReviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.is_additional_reviews
     *
     * @param isAdditionalReviews the value for commodity_reviews.is_additional_reviews
     *
     * @mbggenerated
     */
    public void setIsAdditionalReviews(Byte isAdditionalReviews) {
        this.isAdditionalReviews = isAdditionalReviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.reviews_by
     *
     * @return the value of commodity_reviews.reviews_by
     *
     * @mbggenerated
     */
    public String getReviewsBy() {
        return reviewsBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.reviews_by
     *
     * @param reviewsBy the value for commodity_reviews.reviews_by
     *
     * @mbggenerated
     */
    public void setReviewsBy(String reviewsBy) {
        this.reviewsBy = reviewsBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.reviews_time
     *
     * @return the value of commodity_reviews.reviews_time
     *
     * @mbggenerated
     */
    public Date getReviewsTime() {
        return reviewsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.reviews_time
     *
     * @param reviewsTime the value for commodity_reviews.reviews_time
     *
     * @mbggenerated
     */
    public void setReviewsTime(Date reviewsTime) {
        this.reviewsTime = reviewsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_reviews.content
     *
     * @return the value of commodity_reviews.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_reviews.content
     *
     * @param content the value for commodity_reviews.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }
}