package org.lanmei.sysaop.dao.time_measurement.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table time_measurement
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TimeMeasurement {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_measurement.measurement_id
     *
     * @mbg.generated
     */
    private Integer measurementId;

    /**
     * Database Column Remarks:
     *   执行方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_measurement.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     * Database Column Remarks:
     *   执行方法描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_measurement.method_desc
     *
     * @mbg.generated
     */
    private String methodDesc;

    /**
     * Database Column Remarks:
     *   层：Controller,Service,Other
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_measurement.layer
     *
     * @mbg.generated
     */
    private String layer;

    /**
     * Database Column Remarks:
     *   平均执行时间 MS
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_measurement.avr_time
     *
     * @mbg.generated
     */
    private Long avrTime;

    /**
     * Database Column Remarks:
     *   执行次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_measurement.run_count
     *
     * @mbg.generated
     */
    private Long runCount;

    /**
     * Database Column Remarks:
     *   上一次执行时间 MS
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_measurement.last_time
     *
     * @mbg.generated
     */
    private Long lastTime;

    
    public TimeMeasurement() {
		super();
	}

	public TimeMeasurement(String method, String methodDesc, String layer, Long avrTime, Long runCount, Long lastTime) {
		super();
		this.method = method;
		this.methodDesc = methodDesc;
		this.layer = layer;
		this.avrTime = avrTime;
		this.runCount = runCount;
		this.lastTime = lastTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_measurement.measurement_id
     *
     * @return the value of time_measurement.measurement_id
     *
     * @mbg.generated
     */
    public Integer getMeasurementId() {
        return measurementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_measurement.measurement_id
     *
     * @param measurementId the value for time_measurement.measurement_id
     *
     * @mbg.generated
     */
    public void setMeasurementId(Integer measurementId) {
        this.measurementId = measurementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_measurement.method
     *
     * @return the value of time_measurement.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_measurement.method
     *
     * @param method the value for time_measurement.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_measurement.method_desc
     *
     * @return the value of time_measurement.method_desc
     *
     * @mbg.generated
     */
    public String getMethodDesc() {
        return methodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_measurement.method_desc
     *
     * @param methodDesc the value for time_measurement.method_desc
     *
     * @mbg.generated
     */
    public void setMethodDesc(String methodDesc) {
        this.methodDesc = methodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_measurement.layer
     *
     * @return the value of time_measurement.layer
     *
     * @mbg.generated
     */
    public String getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_measurement.layer
     *
     * @param layer the value for time_measurement.layer
     *
     * @mbg.generated
     */
    public void setLayer(String layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_measurement.avr_time
     *
     * @return the value of time_measurement.avr_time
     *
     * @mbg.generated
     */
    public Long getAvrTime() {
        return avrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_measurement.avr_time
     *
     * @param avrTime the value for time_measurement.avr_time
     *
     * @mbg.generated
     */
    public void setAvrTime(Long avrTime) {
        this.avrTime = avrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_measurement.run_count
     *
     * @return the value of time_measurement.run_count
     *
     * @mbg.generated
     */
    public Long getRunCount() {
        return runCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_measurement.run_count
     *
     * @param runCount the value for time_measurement.run_count
     *
     * @mbg.generated
     */
    public void setRunCount(Long runCount) {
        this.runCount = runCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_measurement.last_time
     *
     * @return the value of time_measurement.last_time
     *
     * @mbg.generated
     */
    public Long getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_measurement.last_time
     *
     * @param lastTime the value for time_measurement.last_time
     *
     * @mbg.generated
     */
    public void setLastTime(Long lastTime) {
        this.lastTime = lastTime;
    }
}